### ISSUE TITLE
Server error on GET: /_data/sensors

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/smartthings.htm.bridge#35]
Getting a 500 error on GET requests.

**Comment by jefffohl** [comment]
Stack trace:
```
127.0.0.1 - - [15/Jan/2016 15:11:00] "GET /_data/sensors HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jefffohl/dev/numenta/smartthings.htm.bridge/runapp.py", line 147, in getSensorList
    return json.dumps(getSensorIds(influxClient.listSensors()))
  File "/Users/jefffohl/dev/numenta/smartthings.htm.bridge/influxclient.py", line 87, in listSensors
    return self.client.get_list_series()
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/influxdb/client.py", line 566, in get_list_series
    rsp = self.query("SHOW SERIES", database=database)
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/influxdb/client.py", line 307, in query
    expected_response_code=expected_response_code
  File "/Users/jefffohl/Library/Python/2.7/lib/python/site-packages/influxdb/client.py", line 223, in request
    raise e
ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))
```

**Comment by jefffohl** [comment]
@rhyolight are you getting this as well?

**Comment by jefffohl** [comment]
I am guessing that the InfluxDB I am referencing is down?

**Comment by rhyolight** [comment]
Yes  it is... Looking into it


---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rhyolight** [comment]
Well now I'm not sure what is wrong. The service looks like it is up, but I
can't connect to it from the command line. I don't know what's wrong, but I
don't think I can look into it until Monday. :(

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
No worries. I will tinker with other things in the meantime, unless you think it might be something I could look into.
